### ISSUE TITLE
--quiet and/or --daemon-mode will not work.

### ISSUE THREAD

**Issue by guisea** [olipo186/Git-Auto-Deploy#118]
I just installed Git-Auto-Deploy. 

Config file
`{
  "pidfilepath": "~/.gitautodeploy.pid",
  "logfilepath": "~/logs/gitautodeploy.log",
  "host": "0.0.0.0",
  "port": 8001,
  "global_deploy": [
    "echo Deploy started!",
    "echo Deploy completed!"
  ],
  "log-level": "INFO",
  "repositories": [
    {
      "url": "git@redactedhost:ansible/agge.git",
      "branch": "master",
      "remote": "origin",
      "path": "~/playbooks/test",
      "deploy": "echo deploying"
    }
  ]
}
`
When starting Git-Autodeploy with --damon-mode --quiet the error below is shown

`Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/ansible/src/Git-Auto-Deploy/gitautodeploy/__main__.py", line 5, in <module>
    main()
  File "/home/ansible/src/Git-Auto-Deploy/gitautodeploy/gitautodeploy.py", line 470, in main
    app.setup(config)
  File "/home/ansible/src/Git-Auto-Deploy/gitautodeploy/gitautodeploy.py", line 258, in setup
    logger.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'
`

**Comment by olipo186** [comment]
Hi,

Are you using an older version of Python? It works with 2.7+.

**Comment by guisea** [comment]
Ahhh,  yes. 2.6.6 on this particular host as it's an old one.  I found a workaround to run it so it is a non-issue now.  In future I will run it with Python > 2.7--ThanksAaron---- On Wed, 06 Jul 2016 22:27:38 +1200  Oliver Poignant<notifications@github.com> wrote ----Hi,  Are you using an older version of Python? It works with 2.7+.  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
